# noinspection ComposeUnknownKeys
include:
  - compose-environment.yml

services:
  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: $APP_CONTAINER_NAME
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_PASSWORD: $POSTGRES_PASSWORD
      DB_USER: $POSTGRES_USER
      DB_NAME: $POSTGRES_DB
      DB_HOST: $DB_CONTAINER_NAME
      DB_PORT: $DB_PORT